import "./globals.css";
import type { Metadata } from "next";
import { Providers } from "@/lib/providers";

import Searchbar from "@/app/components/Searchbar";
import TopPlay from "@/app/TopPlay";
import Sidebar from "@/app/Sidebar";
import PlayerDocker from "./player/PlayerDocker";

export const metadata: Metadata = {
  title: "spotify",
  description: "Generated by spotify app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <Providers>
      <html lang="en">
        <body>
          <div className="relative flex">
            <Sidebar />
            <div className="flex-1 flex flex-col bg-gradient-to-br from-black to-[#121286]">
              <Searchbar />

              <div className="px-6 h-[calc(100vh-72px)] overflow-y-scroll hide-scrollbar flex xl:flex-row flex-col-reverse">
                <div className="flex-1 h-fit pb-40">{children}</div>
                <div className="xl:sticky relative top-0 h-fit">
                  <TopPlay />
                </div>
              </div>
            </div>

            <PlayerDocker />
          </div>
        </body>
      </html>
    </Providers>
  );
}
